name: ohmygin
favicon: null
layout_spectrum: 0.8059435558971018
typography_spectrum: 0.16828824928961694
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3f3f3'
    - '#07060b'
    - '#656871'
    - '#c56d00'
    - '#ffc657'
  brandStrength: 0
  lightness: 0.9959186539053917
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
